name: Test Aiven MySQL

on:
  workflow_dispatch:

jobs:
  test-database:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-app

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Gerar Prisma Client
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma generate

      - name: Testar banco Aiven
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          DATABASE_URL="${DATABASE_URL//ssl-mode=REQUIRED/sslaccept=strict}"
          export DATABASE_URL
          npx prisma db pull --print